info:
  build:
    artifact: 'haxb_partner'
    name: 'haxb_partner'
    description: '信保业务渠道方模块微服务'
    version: '0.0.1-SNAPSHOT'

# database
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//cmisprddb.sinosafe.local:1521/cmisprddb
    username: cmis
    password: cmis_2014
    initialSize: 5
    minIdle: 5
    maxActive: 5
    maxWait: 3000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    removeAbandoned: true
    removeAbandonedTimeout: 600
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  mail:
    host: ds.sinosafe.com.cn
    username: gjzxdk@ds.sinosafe.com.cn
    password: Sno@afe18#
    properties:
      mail: 
          mime.splitlongparameters: false
          smtp: 
            port: 7250
            auth: true
            starttls:
                enable: false
                required: false
  redis: 
    cluster:
      nodes:
        - 10.2.112.26:7000
        - 10.2.112.26:7001
        - 10.2.112.27:7004
        - 10.2.112.27:7005
        - 10.2.112.28:7002
        - 10.2.112.28:7003
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    password: redis2016#
       
#影像系统配置
file: 
  upload: 
    savePath: E:/hastudy/hastudy-app/hastudy-cluster/hastudy/temp/img 
    imageSystem: 
      imgUrl: http://ecmp.sinosafe.com.cn:8080/Interface_Cluster/IImgXmlUpLoadSyn
      fileUrl: http://ecmp.sinosafe.com.cn:8080/TransServer2.0/ISerFIleUp
      imgDomain: https://proxy.sinosafe.com.cn/ecmps/
      imgDomainHttps: https://proxy.sinosafe.com.cn/ecmps/
  canvasPlugPrefix: https://proxy.sinosafe.com.cn/habsl-h5-prd/iframePage2?url=https://proxy.sinosafe.com.cn/haxb_partner_prd/pa/lst_dowload/lsturl/
    
lina:
  dubbo: 
    enable: true
    application:
      name: haxb_partner
    protocol:
      name: dubbo
      port: 208829
    registry:
      address: zookeeper://dubboprd.sinosafe.com.cn:2181
  rabbit: 
    max-consume-retry-count: 5            # if null, will default 3
    multi: 
      exp: 
        host: 10.1.110.19
        port: 5672
        username: xb_credit_app
        password: credit2017
        virtualHost: /xb-credit-app
        publisherConfirms: true 
        publisherReturns: true  
      connection1: 
        host: 10.1.110.19
        port: 5672
        username: xb_credit_app
        password: credit2017
        virtualHost: /xb-credit-app
        publisherConfirms: true 
        publisherReturns: true   
    consumers: 
      messageConsumer: 
        class: cn.com.sinosafe.module.mq.MessageConsumer
        connection: exp
        acknowledge: manual
        prefetch: 5
        concurrency: 10
        max-concurrency: 20
        queue: ha.queue_order_xb_app_service

#邮件发送
mail: 
  #发件人邮箱地址
  from: haxb_partner@sinosafe.com.cn
  #发件人昵称
  personal: 华安信保合作方对接系统
    #异常警报接收人
  reciverAddress: longxiaoqiang@sinosafe.com.cn,ex_xiehanchun@sinosafe.com.cn,ex_zhengbaolei@sinosafe.com.cn
  #异常警报抄送人
  ccAddress: hesong@sinosafe.com.cn,pandeqiang@sinosafe.com.cn  

# 短信配置
sms: 
  url: http://msgplat.sinosafe.com.cn:80/sms/Api/Send.do
  user: H04
  pwd: Hsms04
 
# ftp生产账户及密码、上传下载路径
sftpProperties:
  host: 10.1.102.26
  port: 10226
  account: xb-paphuser
  pwd: XBpahp-2019
  uploadSftpLocation: /upload/lstpath
  dowloadSftpLoacation: /upload/lstpath
  localFileLocation: /upload/lstpath
  
# 保单生产接口地址
issueMsg:
  status: 997
  addr: http://10.1.101.240:8080/cmis-main/MyChannelForHttp
  pattern: 2 
  writtenboard: QT_4542
  lstboard: QT_4543

#马上消费参数
msxf:
  #邮件标题
  mail-title: 【生产环境】-马上消费对接异常
  #是否发送邮件
  mail-send: true
  #华安公钥
  ha-public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCLvJidtCtuyywNhaMzgD1Glo0Kdf4KlyYtB42+8yVkxsWkhunndg4HpcHB+cz5DKYPyusC1tH28smK/KP2CTW10MUtyyfuNUoYyODIoi2Z9/Bdcd6NrADuJznFHAP7FE08LlT50gXLbZGcfO35y/wssrC3QTSzC+xW8o4+blbs8QIDAQAB
  #华安私钥
  ha-private-key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIu8mJ20K27LLA2FozOAPUaWjQp1/gqXJi0Hjb7zJWTGxaSG6ed2DgelwcH5zPkMpg/K6wLW0fbyyYr8o/YJNbXQxS3LJ+41ShjI4MiiLZn38F1x3o2sAO4nOcUcA/sUTTwuVPnSBcttkZx87fnL/CyysLdBNLML7Fbyjj5uVuzxAgMBAAECgYBtrwHUeAHHm67ehlFOMZDngXEADxHzWiVbHxzCD7UAX43v0P508pOcqR1nlx6vNqB6sPq7Zce1oWlVsW05yIzhGA+V/I6WmqlSP0lcsLJngVhHiK63oKnJU0neoEk+Tb58JPz4oJZIpmxGAC4LJ7IzqFthSctfKXF+B/izFTu1iQJBANqSUIQYt8NpyiDcOT+dGe9oSDTLNotHzrXppwSS7Xx5qlyCTDKzUtkTE3nwSgH+LskhX/RaMRAEtWyxHFx3FK8CQQCjqlbkXPCCVrkXGEHSQtOFHSJSadcGwj/vBdbMOk8UH/+5CNgYBGJIK5/9pWCdU5SeAwanz3H8TLc+MF1KTcBfAkEA1QguudFtqmT9wTFkCwCQOqulVO+L5gzDCMMHKooaNmxPA4NryS7G3RSeswbk2zRnXVnOMFeH4lj0i0/EmMrnuQJARx7beYsFnK4Q6n9JAxS1FBBP/N4vaal53OV9rOvdt1Icbwzv0qf9CX2jnbaC4HsUhwGrn7qevtObgXPE5mgZIwJAcw5K/5XU9D0aoHvdOC+uyaTusR65IIt44yRxq5uN3XX/KY8UDx5gBM7seRI3UTOTHb/BpwTnBav+q+v7aBiXxg==
   